server:
 port: 8087

#curl -X POST 127.0.0.1:8087/dongActuator/shutdown
# 1 start-up shutdown
management:
 endpoint:
  shutdown:
   enabled: true
  health:
   show-details: always
# 加载所有的端点/默认只加载了 info / health
 endpoints:
  web:
   exposure:
    include: "*"
# 2 set mine personal shutdown path
   base-path: /dongActuator
#management.endpoints.shutdown.sensitive=false

# 2 set mine personal shutdown port
 server:
  port: 8087
# 3 No external calls allowed
  address: 127.0.0.1
spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  driverClassName: com.mysql.cj.jdbc.Driver
  platform: mysql
  url: jdbc:mysql://127.0.0.1:3306/educational?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
  username: root
  password: root
  initialSize: 5
  minIdle: 1
  maxActive: 20
  maxWait: 60000
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall
 thymeleaf:
  encoding: UTF-8
  cache: false
#redis
#redis begin
 redis:
  host: localhost
  port: 6379
  timeout: 200
  password: 
  # 连接池中的最大空闲连接
  jedis:
   pool:
    max-idle: 8
# 连接池中的最小空闲连接
    min-idle: 0
# 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
# 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
 cache:
  type: redis
#redis end
 rabbitmq:
  host: 127.0.0.1
  port: 5672
  virtual-host: /
  username: guest
  password: guest
  listener:
   simple:
    concurrency: 10
    max-concurrency: 10
    prefetch: 1
    auto-startup: true
    default-requeue-rejected: true
  template:
   retry:
    enabled: true
    initial-interval: 1000
    max-attempts: 3
    max-interval: 10000
    multiplier: 1.0
 mvc:
  favicon:
   enabled: false
# mybatis对应的映射文件路径
mybatis:
 mapper-locations: classpath:mapper/*.xml
# mybatis对应的实体类
 type-aliases-package: com.geek.ms.model
 configuration.map-underscore-to-camel-case: true

pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count\=countSql
#rabbitmq 队列、交换机、路由等参数
seckill:
 queue:
  name: my.queue
 exchange:
  name: my.xechange
  